# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_remove_message_chat_messag_lobby_i_96d6b6_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="is_global",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chat",
            name="dm_pair_key",
            field=models.CharField(
                blank=True,
                help_text="Stable identifier for a 1-on-1 chat (two UUIDs, sorted).",
                max_length=73,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(
                fields=["is_global", "created_at"],
                name="chat_chat_global_created_idx",
            ),
        ),
    ]
