# Generated by Django 5.2.6 on 2026-05-02 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chat_is_global_dm_pair_key'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chat',
            new_name='chat_chat_is_glob_a0825e_idx',
            old_name='chat_chat_global_created_idx',
        ),
    ]
